### ISSUE TITLE
Import annoy Error。。

### ISSUE THREAD

**Issue by ericxk** [spotify/annoy#195]
```
>>> import annoy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/annoy/__init__.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/annoy/annoylib.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/annoy/annoylib.py", line 6, in __bootstrap__
ImportError: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by /home/img/.python-eggs/annoy-1.8.3-py2.7-linux-x86_64.egg-tmp/annoy/annoylib.so)
```

```
$ strings /lib64/libc.so.6 |grep GLIBC_
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_PRIVATE
```

**Comment by erikbern** [comment]
sorry not sure what's going on – did you compile annoy on the same machine as where you're running it?
