### ISSUE TITLE
Windows 7 x64 And Anaconda v5.0.1 - Unable to Install annoy

### ISSUE THREAD

**Issue by wergeld** [spotify/annoy#269]
Using latest (as of yesterday) Anaconda install using python 3.6.4, When I attempt to install via:
`pip install annoy`

I get the following error:

> (Seq2Seq) C:\Users\lrichards>pip install annoy
> Collecting annoy
>   Using cached annoy-1.11.1.tar.gz
> Building wheels for collected packages: annoy
>   Running setup.py bdist_wheel for annoy ... error
>   Complete output from command C:\Users\lrichards\AppData\Local\Continuum\anaco
> da3\envs\Seq2Seq\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Us
> rs\\LRICHA~1\\AppData\\Local\\Temp\\pip-build-xg1qh4j5\\annoy\\setup.py';f=geta
> tr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clos
> ();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\LRICHA~1\AppD
> ta\Local\Temp\tmp25o7_qvdpip-wheel- --python-tag cp36:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-3.6
>   creating build\lib.win-amd64-3.6\annoy
>   copying annoy\__init__.py -> build\lib.win-amd64-3.6\annoy
>   running build_ext
>   building 'annoy.annoylib' extension
>   creating build\temp.win-amd64-3.6
>   creating build\temp.win-amd64-3.6\Release
>   creating build\temp.win-amd64-3.6\Release\src
>   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe /c /nologo
> Ox /W3 /GL /DNDEBUG /MT -IC:\Users\lrichards\AppData\Local\Continuum\anaconda3\
> nvs\Seq2Seq\include -IC:\Users\lrichards\AppData\Local\Continuum\anaconda3\envs
> Seq2Seq\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Inclu
> e" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /EHsc /Tps
> c/annoymodule.cc /Fobuild\temp.win-amd64-3.6\Release\src/annoymodule.obj
>   annoymodule.cc
>   c:\users\lrichards\appdata\local\temp\pip-build-xg1qh4j5\annoy\src\annoylib.h
> 19) : fatal error C1083: Cannot open include file: 'stdio.h': No such file or d
> rectory
>   error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bi
> \\cl.exe' failed with exit status 2
> 
>   ----------------------------------------
>   Failed building wheel for annoy
>   Running setup.py clean for annoy
> Failed to build annoy
> Installing collected packages: annoy
>   Running setup.py install for annoy ... error
>     Complete output from command C:\Users\lrichards\AppData\Local\Continuum\ana
> onda3\envs\Seq2Seq\python.exe -u -c "import setuptools, tokenize;__file__='C:\\
> sers\\LRICHA~1\\AppData\\Local\\Temp\\pip-build-xg1qh4j5\\annoy\\setup.py';f=ge
> attr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.cl
> se();exec(compile(code, __file__, 'exec'))" install --record C:\Users\LRICHA~1\
> ppData\Local\Temp\pip-s36zmsav-record\install-record.txt --single-version-exter
> ally-managed --compile:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.6
>     creating build\lib.win-amd64-3.6\annoy
>     copying annoy\__init__.py -> build\lib.win-amd64-3.6\annoy
>     running build_ext
>     building 'annoy.annoylib' extension
>     creating build\temp.win-amd64-3.6
>     creating build\temp.win-amd64-3.6\Release
>     creating build\temp.win-amd64-3.6\Release\src
>     C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\cl.exe /c /nolog
>  /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\lrichards\AppData\Local\Continuum\anaconda
> \envs\Seq2Seq\include -IC:\Users\lrichards\AppData\Local\Continuum\anaconda3\en
> s\Seq2Seq\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Inc
> ude" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /EHsc /T
> src/annoymodule.cc /Fobuild\temp.win-amd64-3.6\Release\src/annoymodule.obj
>     annoymodule.cc
>     c:\users\lrichards\appdata\local\temp\pip-build-xg1qh4j5\annoy\src\annoylib
> h(19) : fatal error C1083: Cannot open include file: 'stdio.h': No such file or
> directory
>     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\
> in\\cl.exe' failed with exit status 2
> 
>     ----------------------------------------
> Command "C:\Users\lrichards\AppData\Local\Continuum\anaconda3\envs\Seq2Seq\pyth
> n.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\LRICHA~1\\AppData
> \Local\\Temp\\pip-build-xg1qh4j5\\annoy\\setup.py';f=getattr(tokenize, 'open',
> pen)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code,
> __file__, 'exec'))" install --record C:\Users\LRICHA~1\AppData\Local\Temp\pip-s
> 6zmsav-record\install-record.txt --single-version-externally-managed --compile"
> failed with error code 1 in C:\Users\LRICHA~1\AppData\Local\Temp\pip-build-xg1q
> 4j5\annoy\

There is no annoy package available via Conda for Windows and no package listed in Anaconda Navigator.

How can I get this lib installed under Window?

**Comment by erikbern** [comment]
sounds like you don't have stdio.h on your computer so something is probably messed up with your compiler

i haven't used conda/anaconda but probably makes sense to upload a binary from appveyor at some point (given that i don't have access to a windows system)

**Comment by wergeld** [comment]
Seems odd that I would not have stdio.h from Visual Studio as I have VS 2015 (and 2013) installed and do other projects from within it. Will do more digging on that but a binary would be really helpful if/when you have time.

**Comment by erikbern** [comment]
Cool. Found this which seems like it could be useful: https://github.com/rmcgibbo/python-appveyor-conda-example

**Comment by wergeld** [comment]
I checked - I have many stdio.h files. Some from R builds, some from mingw, some from conda, and, of course from Visual Studio. I have:
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\cl.exe in my Path (it is used in build as seen in log).
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include - many header files including stdio.h.

So, not really sure how to resolve currently.

**Comment by tjrileywisc** [comment]
@wergeld 
It appears that the VS 2012 compiler is selected when you run `setup.py install` (you almost certainly should be using the VS 2015 compiler for python 3.6)

Not sure where setuptools selects the compiler, but I'm fairly sure your problem is there.

**Comment by erikbern** [comment]
yeah if anyone can help me with conda, would appreciate it!

**Comment by AsmaZbt** [comment]
pip install annoy
Collecting annoy
Exception:
Traceback (most recent call last):
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\twins\Anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=True,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
i've used cygwin64

**Comment by AsmaZbt** [comment]
in the file index.py this is the function : 
class HTMLPage(object):
    """Represents one page, along with its URL"""

    def __init__(self, content, url, headers=None):
        # Determine if we have any encoding information in our headers
        encoding = None
        if headers and "Content-Type" in headers:
            content_type, params = cgi.parse_header(headers["Content-Type"])

            if "charset" in params:
                encoding = params['charset']

        self.content = content
        self.parsed = html5lib.parse(
            self.content,
            transport_encoding=encoding,
            namespaceHTMLElements=False,
        )
        self.url = url
        self.headers = headers

    def __str__(self):
        return self.url

**Comment by AsmaZbt** [comment]
i changed transport_encoding to encoding it's ok ,
but this the problem that i get even with git , cmd , visualC++command prompt : 
Generating code
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    ----------------------------------------
Command "C:\Users\twins\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\cygwin64\\tmp\\pip-build-7j698hpp\\annoy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\cygwin64\tmp\pip-tmxbv_uu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\cygwin64\tmp\pip-build-7j698hpp\annoy\

**Comment by AsmaZbt** [comment]
oh finally it's work so happy :)
thank you so much for the library 
I've applied the process described in your site: https://ci.appveyor.com/project/erikbern/annoy 

i've a problem : LINK : fatal error LNK1158: cannot run 'rc.exe' error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

and the solotion here : https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe

thank you

**Comment by erikbern** [comment]
ok, i'll see if i can automate the process somehow!

**Comment by JThinkable** [comment]
After installing Build Tools for Visual Studio 2017 from https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017 I got a similar error:
> annoylib.h(19): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
Initially I did not include the Windows 10 SDK.  After including just that component, the compile went without a hitch.

**Comment by NikilRagav** [comment]
@erikbern I'm looking at the appveyor page trying to build this. It seems like you have a script but I can't figure out where to download the script.

I'm using Anaconda on Windows 10.  It looks like my system environment vars don't currently include "PYTHON=C:\Python36-x64, PYTHON_VERSION=3.6.5, PYTHON_ARCH=64"
Am I supposed to add that?

I had read somewhere in Anaconda docs that you're not supposed to use pip and conda together - so I am confused about how to build this and link it to Anaconda

**Comment by SirJAKfromSpace** [comment]
@JThinkable 
Hi I've also been having trouble with the exact same error. Can you please a a bit more specific as to which components you installed? A screenshot perhaps would be very helpful. Thanks

**Comment by JThinkable** [comment]
@SirJAKfromSpace 

1. I downloaded vs_buildtools_*.exe from the link https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017.
![image](https://user-images.githubusercontent.com/4322932/48270137-4f3b7200-e407-11e8-9ae3-554ca08eac35.png)

2. Run the executable, eventually you'll get to the "Visual Studio Installer" which should have a section "Visual Studio Build Tools 2017".  "Install" or "Modify" that.
![image](https://user-images.githubusercontent.com/4322932/48270069-17342f00-e407-11e8-9732-2cf2a64ccc13.png)
![image](https://user-images.githubusercontent.com/4322932/48270030-fff54180-e406-11e8-8b77-89a00abc46dd.png)

3. On the right side of the dialog, one of the **optional** components is "Windows 10 SDK (10.0.17134.0)"  I doubt the minor version numbers matter much.  Make sure you install it.
![image](https://user-images.githubusercontent.com/4322932/48269993-ea801780-e406-11e8-9b0b-aa86f455f9c8.png)

**Comment by SirJAKfromSpace** [comment]
@JThinkable thank you for the info, but its STILL telling me the same thing. Driving me crazy.
I checked the environment variables too if thats what youre thinking. Anywho it built ok on my laptop rather than my desktop so thanks anyway.

**Comment by PymatFlow** [comment]
Hello
I found the solution for installing annoy in anaconda and windows.
The solution is mainly in the [https://wiki.python.org/moin/WindowsCompilers](https://wiki.python.org/moin/WindowsCompilers)

This problem does not happen in Linux, but windows does not have C++ compilers in some cases and you should install it by yourself.

1 ) run the following command :  install or upgrade the Setuptools Python package

`pip install --upgrade setuptools
`

2 ) go the following link 
[https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2019](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2019
)

and download the **Build Tools for Visual Studio 2019**

These Build Tools allow you to build Visual Studio projects from a command-line interface. Supported projects include: ASP.NET, Azure, C++ desktop, ClickOnce, containers, .NET Core, .NET Desktop, Node.js, Office and SharePoint, Python, TypeScript, Unit Tests, UWP, WCF, and Xamarin.



![aks11](https://user-images.githubusercontent.com/18423968/70785765-6bdf7180-1da0-11ea-8799-35402cd8a2c1.jpg)


3 ) install **Build Tools for Visual Studio 2019**

![aks22](https://user-images.githubusercontent.com/18423968/70785915-af39e000-1da0-11ea-8846-06bd650bc945.jpg)


during the installation, select the following items 

![aks333](https://user-images.githubusercontent.com/18423968/70786060-063fb500-1da1-11ea-95c4-cf7543caee78.jpg)



4) restart your system (PC)


5) run the following command in **Anaconda prompt** 

`pip install --user annoy
`

![aks44](https://user-images.githubusercontent.com/18423968/70786349-bca39a00-1da1-11ea-9078-96229f194518.jpg)


Now you can use annoy in your python code.

**Comment by erikbern** [comment]
nice! i'll see if there's a way to precompile a binary package using appveyor
