### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal not in range(128)

### ISSUE THREAD

**Issue by allieonpoppyfield** [spotify/annoy#352]
I can not install annoy on python 2.7

C:\Python27\Scripts\pip.exe install annoy

Running setup.py install for annoy ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\836d~1\\appdata\\local\\temp\\pip-install-dy79vf\\annoy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\836d~1\appdata\local\temp\pip-record-bm8azy\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\annoy
    copying annoy\__init__.py -> build\lib.win-amd64-2.7\annoy
    running build_ext
    building 'annoy.annoylib' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\836d~1\appdata\local\temp\pip-install-dy79vf\annoy\setup.py", line 82, in <module>
        setup_requires=['nose>=1.0']
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\python27\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\python27\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "c:\python27\lib\site-packages\setuptools\command\build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\python27\lib\distutils\command\build_ext.py", line 498, in build_extension
        depends=ext.depends)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 148, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1257, in return_env
        exists),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1280, in _build_paths
        return os.pathsep.join(unique_paths)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal not in range(128)

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\836d~1\\appdata\\local\\temp\\pip-install-dy79vf\\annoy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\836d~1\appdata\local\temp\pip-record-bm8azy\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\836d~1\appdata\local\temp\pip-install-dy79vf\annoy\

**Comment by erikbern** [comment]
this error seems unrelated to annoy!

**Comment by erikbern** [comment]
it's probably related to the compilation of annoy
