### ISSUE TITLE
Failing angular distance tests

### ISSUE THREAD

**Issue by karlhigley** [spotify/annoy#432]
When I clone master at v1.16.2 and run the tests, I get two failures with Python 2.7.16:

```
======================================================================
FAIL: test_distance_consistency (angular_index_test.AngularIndexTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/Projects/ml/annoy/test/angular_index_test.py", line 196, in test_distance_consistency
    self.assertAlmostEqual(dist, numpy.dot(u_norm - v_norm, u_norm - v_norm) ** 0.5)
  File "/Users/karl/Projects/ml/annoy/test/common.py", line 20, in assertAlmostEqual
    super(TestCase, self).assertAlmostEqual(x, y, 3)
AssertionError: 0.0005146485636942089 != 0.0 within 3 places

======================================================================
FAIL: test_single_vector (angular_index_test.AngularIndexTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/Projects/ml/annoy/test/angular_index_test.py", line 226, in test_single_vector
    self.assertEquals(a.get_nns_by_vector([1, 0, 0], 3, include_distances=True), ([0], [0.0]))
AssertionError: Tuples differ: ([0], [0.0003452669770922512]) != ([0], [0.0])

First differing element 1:
[0.0003452669770922512]
[0.0]

- ([0], [0.0003452669770922512])
+ ([0], [0.0])

----------------------------------------------------------------------
Ran 99 tests in 175.784s

FAILED (failures=2)
```

Any ideas why these tests would be failing? (With Python 3.7.4, only the second test fails.)

The Python 2 build logs look like this:

```
$ python setup.py nosetests
running nosetests
running egg_info
writing annoy.egg-info/PKG-INFO
writing top-level names to annoy.egg-info/top_level.txt
writing dependency_links to annoy.egg-info/dependency_links.txt
reading manifest file 'annoy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'annoy.egg-info/SOURCES.txt'
building 'annoy.annoylib' extension
creating build/temp.macosx-10.14-x86_64-2.7
creating build/temp.macosx-10.14-x86_64-2.7/src
clang -fno-strict-aliasing -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/karl/.pyenv/versions/2.7.16/include/python2.7 -c src/annoymodule.cc -o build/temp.macosx-10.14-x86_64-2.7/src/annoymodule.o -march=native -O3 -ffast-math -fno-associative-math -std=c++11 -mmacosx-version-min=10.9
In file included from src/annoymodule.cc:15:
src/annoylib.h:81:9: warning: Using 128-bit AVX instructions [-W#pragma-messages]
#pragma message "Using 128-bit AVX instructions"
        ^
In file included from src/annoymodule.cc:17:
In file included from /Users/karl/.pyenv/versions/2.7.16/include/python2.7/Python.h:88:
/Users/karl/.pyenv/versions/2.7.16/include/python2.7/unicodeobject.h:534:5: warning: 'register'
      storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register PyObject *obj,     /* Object */
    ^~~~~~~~~
/Users/karl/.pyenv/versions/2.7.16/include/python2.7/unicodeobject.h:553:5: warning: 'register'
      storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register PyObject *obj      /* Object */
    ^~~~~~~~~
/Users/karl/.pyenv/versions/2.7.16/include/python2.7/unicodeobject.h:575:5: warning: 'register'
      storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register const wchar_t *w,  /* wchar_t buffer */
    ^~~~~~~~~
/Users/karl/.pyenv/versions/2.7.16/include/python2.7/unicodeobject.h:593:5: warning: 'register'
      storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register wchar_t *w,        /* wchar_t buffer */
    ^~~~~~~~~
In file included from src/annoymodule.cc:17:
In file included from /Users/karl/.pyenv/versions/2.7.16/include/python2.7/Python.h:97:
/Users/karl/.pyenv/versions/2.7.16/include/python2.7/stringobject.h:173:5: warning: 'register'
      storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register PyObject *obj,     /* string or Unicode object */
    ^~~~~~~~~
/Users/karl/.pyenv/versions/2.7.16/include/python2.7/stringobject.h:174:5: warning: 'register'
      storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register char **s,          /* pointer to buffer variable */
    ^~~~~~~~~
/Users/karl/.pyenv/versions/2.7.16/include/python2.7/stringobject.h:175:5: warning: 'register'
      storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register Py_ssize_t *len    /* pointer to length variable or NULL
    ^~~~~~~~~
8 warnings generated.
creating build/lib.macosx-10.14-x86_64-2.7
creating build/lib.macosx-10.14-x86_64-2.7/annoy
c++ -bundle -undefined dynamic_lookup -L/Users/karl/.homebrew/opt/readline/lib -L/Users/karl/.homebrew/opt/readline/lib -L/Users/karl/.homebrew/opt/openssl/lib -L/Users/karl/.pyenv/versions/2.7.16/lib build/temp.macosx-10.14-x86_64-2.7/src/annoymodule.o -o build/lib.macosx-10.14-x86_64-2.7/annoy/annoylib.so -stdlib=libc++ -mmacosx-version-min=10.9
copying build/lib.macosx-10.14-x86_64-2.7/annoy/annoylib.so -> annoy
```
The only thing that stands out to me there is the warning about 128-bit AVX instructions, but not sure if that's related.

**Comment by erikbern** [comment]
weird, but looks like it’s caused by some kind of rounding issue

**Comment by erikbern** [comment]
i think this is easy to fix by just making sure the max allowable delta is a bit larger

but the magnitude of the delta makes me a bit nervous – it's 5e-4 and 3e-4 respectively. seems a lot larger than what could be easily explained by floating point precision issues

**Comment by karlhigley** [comment]
Poking around in the angular distance computation for that test, I'm seeing:

```
pp: 1.00000000
qq: 1.00000000
pq: 1.00000000
ppqq: 1.00000000
distance: 0.00000012
normalized distance: 0.00034527
```

The distance itself might just be rounding error that gets magnified by the `sqrt`?

**Comment by erikbern** [comment]
oh, that's right, thanks a lot for convincing me that sqrt is the culprit here. 

it's probably easy to fix by just squaring the two arguments here: https://github.com/spotify/annoy/blob/master/test/angular_index_test.py#L196 and L198

and for the other test, probably just have to rewrite it to loop over the components and use `assertAlmostEquals`

feel free to submit a PR, or i could also look at it later this week

**Comment by karlhigley** [comment]
Thanks, I'll give that a try.
