### ISSUE TITLE
Some segment faults

### ISSUE THREAD

**Issue by aivul** [spotify/annoy#653]
Hi, I notice some comments said "TODO: handle OOB" in the source code such as https://github.com/spotify/annoy/blob/main/src/annoylib.h#L1147, and the bugs are still exist in the latest version.

I have found another one in function `manhattan_distance`

```c
#include <iostream>
#include <iomanip>
#include "../src/kissrandom.h"
#include "../src/annoylib.h"
#include <chrono>
#include <algorithm>
#include <map>
#include <random>

using namespace Annoy;
int main(){
        int f = 10;

        AnnoyIndex<int, double, Manhattan, Kiss32Random, AnnoyIndexMultiThreadedBuildPolicy> t = AnnoyIndex<int, double, Manhattan, Kiss32Random, AnnoyIndexMultiThreadedBuildPolicy>(f);
        for(int i=0; i<30; ++i){
                double *vec = (double *) malloc(f * sizeof(double) );
                for(int z=0; z<f; ++z){
                        vec[z] = 0.1;
                }
                t.add_item(i, vec);
        }
        t.build(2 * f);

        t.get_distance(0x41414141, 1); //Here

        return 0;
}

```

run 

```
clang++-15 test.cpp -DANNOYLIB_MULTITHREADED_BUILD -std=c++14 -pthread -o test -fsanitize=address,fuzzer -g -O0
ASAN_OPTIONS="detect_leaks=0" ./test
```

the crash info 

```

Thread 1 "oob" received signal SIGSEGV, Segmentation fault.
0x00005555555566d2 in Annoy::(anonymous namespace)::manhattan_distance<double> (x=0x556fd7dac400, y=0x555555584200, f=0xa) at ./../src/annoylib.h:187
187         d += fabs(x[i] - y[i]);
[ Legend: Modified register | Code | Heap | Stack | String ]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
$rax   : 0x556fd7dac400
$rbx   : 0x0
$rcx   : 0x0
$rdx   : 0xa
$rsp   : 0x00007fffffffe3b0  →  0x00007fffffffe3e0  →  0x00007fffffffe410  →  0x00007fffffffe4e0  →  0x0000000000000001
$rbp   : 0x00007fffffffe3b0  →  0x00007fffffffe3e0  →  0x00007fffffffe410  →  0x00007fffffffe4e0  →  0x0000000000000001
$rsi   : 0x0000555555584200  →  0x3fb999999999999a
$rdi   : 0x556fd7dac400
$rip   : 0x00005555555566d2  →  <double+0> movsd xmm0, QWORD PTR [rax+rcx*8]
$r8    : 0x0000555555584180  →  0x0000000000000001
$r9    : 0x00007fffdffdf640  →  0x00007fffdffdf640  →  [loop detected]
$r10   : 0x00007ffff7fc36c8  →  0x000d001200000099
$r11   : 0x89fa28cd0894df04
$r12   : 0x00007fffffffe5f8  →  0x00007fffffffe7f1  →  "/root/target/annoy/examples/oob"
$r13   : 0x0000555555556460  →  <main+0> push rbp
$r14   : 0x000055555556ac10  →  0x0000555555556410  →  <__do_global_dtors_aux+0> endbr64
$r15   : 0x00007ffff7ffd040  →  0x00007ffff7ffe2e0  →  0x0000555555554000  →   jg 0x555555554047
$eflags: [zero CARRY PARITY ADJUST SIGN trap INTERRUPT direction overflow RESUME virtualx86 identification]
$cs: 0x33 $ss: 0x2b $ds: 0x00 $es: 0x00 $fs: 0x00 $gs: 0x00
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stack ────
0x00007fffffffe3b0│+0x0000: 0x00007fffffffe3e0  →  0x00007fffffffe410  →  0x00007fffffffe4e0  →  0x0000000000000001      ← $rsp, $rbp
0x00007fffffffe3b8│+0x0008: 0x000055555555937b  →  <double+0> add rsp, 0x20
0x00007fffffffe3c0│+0x0010: 0x00007fffffffe3e0  →  0x00007fffffffe410  →  0x00007fffffffe4e0  →  0x0000000000000001
0x00007fffffffe3c8│+0x0018: 0x0000000a55557c73 ("s|UU\n"?)
0x00007fffffffe3d0│+0x0020: 0x00005555555841e8  →  0x0000000000000001
0x00007fffffffe3d8│+0x0028: 0x0000556fd7dac3e8
0x00007fffffffe3e0│+0x0030: 0x00007fffffffe410  →  0x00007fffffffe4e0  →  0x0000000000000001
0x00007fffffffe3e8│+0x0038: 0x0000555555556fc5  →  <Annoy::AnnoyIndex<int,+0> call 0x5555555594d0 <_ZN5Annoy9Manhattan19normalized_distanceIdEET_S2_>
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── code:x86:64 ────
   0x5555555566c4 <double+0>       jge    0x555555556707 <_ZN5Annoy12_GLOBAL__N_118manhattan_distanceIdEET_PKS2_S4_i+103>
   0x5555555566ca <double+0>       mov    rax, QWORD PTR [rbp-0x8]
   0x5555555566ce <double+0>       movsxd rcx, DWORD PTR [rbp-0x24]
 → 0x5555555566d2 <double+0>       movsd  xmm0, QWORD PTR [rax+rcx*8]
   0x5555555566d7 <double+0>       mov    rax, QWORD PTR [rbp-0x10]
   0x5555555566db <double+0>       movsxd rcx, DWORD PTR [rbp-0x24]
   0x5555555566df <double+0>       subsd  xmm0, QWORD PTR [rax+rcx*8]
   0x5555555566e4 <double+0>       movaps xmm1, XMMWORD PTR [rip+0xc965]        # 0x555555563050
   0x5555555566eb <double+0>       pand   xmm0, xmm1
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── source:./../src/annoylib.h+187 ────
    182
    183  template<typename T>
    184  inline T manhattan_distance(const T* x, const T* y, int f) {
    185    T d = 0.0;
    186    for (int i = 0; i < f; i++)
             // i=0x0, x=0x00007fffffffe3a8  →  0x0000556fd7dac400, y=0x00007fffffffe3a0  →  [...]  →  0x3fb999999999999a
 →  187      d += fabs(x[i] - y[i]);
    188    return d;
    189  }
    190
    191  template<typename T>
    192  inline T euclidean_distance(const T* x, const T* y, int f) {
[!] Command 'context' failed to execute properly, reason: 'threads'
Python Exception <class 'UnicodeEncodeError'>: 'ascii' codec can't encode character '\u27a4' in position 12: ordinal not in range(128)
(gdb) bt
#0  0x00005555555566d2 in Annoy::(anonymous namespace)::manhattan_distance<double> (x=0x556fd7dac400, y=0x555555584200, f=0xa) at ./../src/annoylib.h:187
#1  0x000055555555937b in Annoy::Manhattan::distance<int, double> (x=0x556fd7dac3e8, y=0x5555555841e8, f=0xa) at ./../src/annoylib.h:798
#2  0x0000555555556fc5 in Annoy::AnnoyIndex<int, double, Annoy::Manhattan, Annoy::Kiss32Random, Annoy::AnnoyIndexMultiThreadedBuildPolicy>::get_distance (this=0x7fffffffe468, i=0x41414141, j=0x1) at ./../src/annoylib.h:1143
#3  0x000055555555658b in main () at oob.cpp:33
```

**Comment by erikbern** [comment]
Yeah annoy doesn't perform bounds check – it's the caller's responsibility right now
